org.gradle.parallel=true

spinnakerGradleVersion=8.32.1
pf4jVersion=3.10.0
korkVersion=2025.11.11.00.09.23.main
# The service versions listed below are not needed for the actual plugin to function
# but are being added in order to enable plugin compatibility testing for the plugin
clouddriverVersion=2025.11.11.00.09.23.main
echoVersion=2025.11.11.00.09.23.main
fiatVersion=2025.11.11.00.09.23.main
front50Version=2025.11.11.00.09.23.main
gateVersion=2025.11.11.00.09.23.main
igorVersion=2025.11.11.00.09.23.main
kayentaVersion=2025.11.11.00.09.23.main
orcaVersion=2025.11.11.00.09.23.main
roscoVersion=2025.11.11.00.09.23.main

targetJava17=true

# TODO figure this out (hint, we need the following: https://github.com/spinnaker/kork/pull/592/files)
clouddriverMinimumSuppotedVersion=0.0.0
echoMinimumSuppotedVersion=0.0.0
fiatMinimumSuppotedVersion=0.0.0
front50MinimumSuppotedVersion=0.0.0
gateMinimumSuppotedVersion=0.0.0
igorMinimumSuppotedVersion=0.0.0
kayentaMinimumSuppotedVersion=0.0.0
orcaMinimumSuppotedVersion=0.0.0
roscoMinimumSuppotedVersion=0.0.0
