name: Build CD Images

on:
  push:
    branches:
      - master
      - "release-[0-9]+.[0-9]+.x"

jobs:
  publish_images:
    runs-on: ubuntu-latest
    env:
      HARNESS_ARTIFACT_PASSWORD: ${{secrets.HARNESS_ARTIFACTORY_PASSWORD}}
      GRADLE_ARGS: -Pharness_artifact_user=${{secrets.HARNESS_ARTIFACTORY_USER}} -Pharness_artifact_password=${{secrets.HARNESS_ARTIFACTORY_PASSWORD}}
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
          cache: 'gradle'

      - name: build
        run: ./gradlew -PenableCrossCompilerPlugin=true releaseBundle $GRADLE_ARGS

      - name: archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/distributions

      - name: generate variables
        id: variables
        uses: armory-io/astrolabe-build-defaults@main

      - name: build docker image
        id: build-docker-image
        run: |
          docker build -t ${{ steps.variables.outputs.artifactory_image_name }} -f build-tools/Dockerfile .
