name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      HARNESS_ARTIFACT_PASSWORD: ${{secrets.HARNESS_ARTIFACTORY_PASSWORD}}
      ORG_GRADLE_PROJECT_harness_artifact_user: '${{secrets.HARNESS_ARTIFACTORY_USER}}'
      ORG_GRADLE_PROJECT_harness_artifact_password: '${{secrets.HARNESS_ARTIFACTORY_PASSWORD}}'
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: |
            11
          cache: 'gradle'
          distribution: 'temurin'
      - name: run tests
        run: |
          ./gradlew test
      - name: build
        run: |
          ./gradlew -PenableCrossCompilerPlugin=true releaseBundle
      - name: archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/distributions